---
  - name: install tools
    apt: name={{item}} state=latest update_cache=yes
    loop: ['python-mysqldb,python3-mysqldb']
    tags: install tools

  - name: install mysql-server
    apt: name=mysql-server state=present update_cache=yes
    tags: mysql

  - name: ensure mysql started 
    service: name=mysql state=started enabled=yes
    tags: mysql

  - name: Copy database dump file
    copy: src=demo/app/init.sql dest=/tmp

  - name: create demo db
    mysql_db: name={{db_name}} state=import target=/tmp/init.sql
    tags: mysql

  - name: create demo db user
    mysql_user: name={{db_user_name}} password={{db_user_pass}} priv='*.*:ALL,GRANT' host='%'
    tags: mysql
    notify: restart mysql


    
  - name: ensure mysql listening on all ports 
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
                line="bind-address = 0.0.0.0"
    notify: restart mysql